### ISSUE TITLE
Audio?

### ISSUE THREAD

**Issue by ksenesaynho** [learn-co-curriculum/building-responsive-sites#1]
is there supposed to be audio for this slide? i can't hear anything.

**Comment by maxwellbenton** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.  The video linked in this repository has working audio.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
