### ISSUE TITLE
Quick Fix: Extra "to" in text

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/building-responsive-sites#13]
2nd line has a 'to' that's not needed.  (Not trying to be a smarty pants with these adjustments; just want Flatiron to present in the best possible way.  Luv you guys! Deep respect for the lessons, too. )
****************

**Creating Responsive Sites with CSS**
The other common solution to is to use Cascading Style Sheets

**Comment by jenmyers** [comment]
Resolved.
