### ISSUE TITLE
Grammar edits in text

### ISSUE THREAD

**Issue by ivillicana** [learn-co-curriculum/building-responsive-sites#3]
WHAT IS MOBILE-UP DESIGN
Going in the opposite direction is mobile-up or mobile-first, an approach gaining popularity in our modern, mobile world. The idea behind this approach is to design websites for small screen sizes first. One benefit to this approach is that it ensures users have a great experience on mobile, **as there is no change it will end up being a second thought during design**. ???

Many, if not most, internet users now interact ~~with the~~ through their cell phones more than their laptops, so it makes sense for businesses to cater to these users first. Chrome luckily provides a useful tool, the device toolbar within the developer tools, that lets you mimic the proportions of popular mobile devices.

Mobile-up design means that, by default, elements on the page ~~are positioned~~ are positioned and sized for small screens, then overridden if a larger screen is detected.

**Comment by jenmyers** [comment]
Resolved.
