### ISSUE TITLE
A few more grammar issues

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/building-responsive-sites#7]
You have "What is Desktop-Down Design?" and "What is Mobile-Up Design" -- the latter without a question mark. You could add a question mark to the second one, or probably best to remove the "What is" and question mark from both.

"Explain Graceful Degradation" and "Explain Progressive Enhancement" -- you could change both to a "What is?" format to match the two above, or change both to "Explaining," but I think the best option would be to just remove the "Explain" from each one.

I submit all of these as suggestions because I'm not sure if Flatiron has a style manual, and/or what your specifications are.

Thank you!

**Comment by jenmyers** [comment]
Resolved.
