### ISSUE TITLE
Refactoring this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/building-responsive-sites#8]
"Graceful degradation is the practice of designing a web page for modern browsers, but providing 'fall back' versions, alternative designs that have less features, but still provide a good experience."

Suggested improvement:
"Graceful degradation is the practice of designing a web page for modern browsers, but providing fallback versions. Fallback versions are alternative designs that have fewer features, but still provide a good experience."

In sum, fallback is a word, and if things are countable, use "fewer," not "less."

Thank you.

**Comment by jenmyers** [comment]
Resolved.
